# Generated by Django 4.2.7 on 2023-11-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_localstore_supplier_alter_material_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviment",
            name="status",
            field=models.CharField(
                choices=[(1, "entrada"), (2, "saída")], max_length=10
            ),
        ),
    ]
