# Generated by Django 4.2.7 on 2023-11-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_material_options_alter_moviment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviment',
            name='status',
            field=models.CharField(choices=[('entrada', 'entrada'), ('saída', 'saída')], max_length=10),
        ),
    ]
